### ISSUE TITLE
Handle Severity Profiles

### ISSUE THREAD

**Issue by bourgesl** [JMMC-OpenDev/OITools#1]
Describe the needs:
Severity profiles mark validation failures with the appropriate severity: INFO, WARNING, ERROR

**Comment by Hitogoroshi** [comment]
Define the logical rules to choose which config files to use which correctly define the severity profile in the given case: 
http://www.jmmc.fr/twiki/bin/view/Jmmc/Software/JmmcOiToolsRoadmap#2_Define_error_profiles

**Comment by bourgesl** [comment]
Implemented and released in OIFitsExplorer beta:
http://jmmc.fr/~betaswmgr/OIFitsExplorer/
