### ISSUE TITLE
OI_INSPOL missing in description in xml output

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/OITools#11]
Check and correct the presence of OI_INSPOL in the xml output in XmlOutputVisitor

**Comment by Hitogoroshi** [comment]
Checked OI_INSPOl present on the Xml

**Comment by bourgesl** [comment]
What's next ?

**Comment by Hitogoroshi** [comment]
OI_INSPOL is present in the Xml output
