### ISSUE TITLE
Create Method to get the OIFITS standard of the OIFitsFile

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/OITools#12]
FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(FitsConstants.KEYWORD_CONTENT) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1) is used 4 time !

Proposal: 
    /**
     * define the version of the file
     *
     * @return the version
     */
    public OIFitsStandard defineOIFITSVersion() {
        return (FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(FitsConstants.KEYWORD_CONTENT) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1);
    }

**Comment by bourgesl** [comment]
It looks strange !

The expression "FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(FitsConstants.KEYWORD_CONTENT) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1)" is CONSTANT !

C1.equals(C2) ? V1 : V2 => V1 or V2 !

Please verify the use cases.

You would need instead:
public OIFitsStandard getOIFitsStandard(String content) {
    return (FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(content) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1);
}

**Comment by Hitogoroshi** [comment]
Right.
Last problem is where to place the method.
We have a use like this when oifitsfile does not exist yet.

**Comment by bourgesl** [comment]
Make a static public method in the appropriate class ...

"We have a use like this when oifitsfile does not exist yet."
Alright, what is your proposal ?

**Comment by Hitogoroshi** [comment]
In OIFITSFILE:
use : (FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(FitsConstants.KEYWORD_CONTENT) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1) to define version. (2 times)

In OIFITSLOADER:
use: (FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(content) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1) to define version of OIFITS
with content = header.getTrimmedStringValue(FitsConstants.KEYWORD_CONTENT) ( 2 times)

**Comment by bourgesl** [comment]
Check & verify the OIFITSFILE as it looks buggy !

**Comment by Hitogoroshi** [comment]
Question related to the review of the method:
inspectRuleFailed(final Rule rule, final String applyTo, final OIFitsStandard standard)

Maybe new issue

**Comment by bourgesl** [comment]
I still do not understand anything...

**Comment by gmella** [comment]
Yes, what is the question related to the review of the method ?

**Comment by Hitogoroshi** [comment]
Create Method to define version of the File in OIFitsFile done:
getOIFitsStandard(content)

**Comment by bourgesl** [comment]
still waiting for patch

**Comment by Hitogoroshi** [comment]
We have in OiFitsFile a comparison with constants (used two times):

(FitsConstants.KEYWORD_CONTENT_OIFITS2.equals(FitsConstants.KEYWORD_CONTENT) ? OIFitsStandard.VERSION_2 : OIFitsStandard.VERSION_1)

We need to check its effect

Proposal:
Can delete the method : checker.inspectRuleFailed() (Special case which catch the failures using directly the applyTo and version information)

To

checker.ruleFailed(Rule.OIFITS_OI_TARGET_EXIST);
which now can process rules begin with OIFITS (And add "FILE" in the applyTo for this rules).

**Comment by bourgesl** [comment]
Fix pushed
