### ISSUE TITLE
No error if DIM COL <= DIM MAX COL

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/OITools#20]
Lenient Format. In ColumnMeta.java

Actual:
if (columnRepeat != descRepeat)

Proposal:
if (columnRepeat <= descRepeat)

**Comment by bourgesl** [comment]
Why ? What is the problem ? 
Maybe for strings, but for anything else NO, I do not see any good argument in favor of such change

**Comment by bourgesl** [comment]
No more applicable.
