### ISSUE TITLE
Derived columns need to use method getMinMaxColumnValue()

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/OITools#25]
Method getMinMaxColumnValue(final String name) return the minimum and maximum column value given its name. The returned value can be null if the column has never been defined.
This method is defined in FitsTable and used some getColumnAs() to find the values.

To improve the method, it should be rewritten to take into account getDerivedColumnAs().

**Comment by bourgesl** [comment]
invalid
