### ISSUE TITLE
Review the Rule message for UNIT_EXIST

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/OITools#3]
Actual : "Missing unit for column '{{MEMBER}}', should be not empty or '{{VALUE}}'"

**Comment by Hitogoroshi** [comment]
Proposal : "Missing unit for column '{{MEMBER}}', should be '{{VALUE}}'"

**Comment by bourgesl** [comment]
No, that's not better !
Please review the rule code to see what it does and then propose a better message

**Comment by Hitogoroshi** [comment]
Proposal : "Missing unit for column '{{MEMBER}}', should be not empty"
The error is only generated if there is no unit...

**Comment by Hitogoroshi** [comment]
commit !
