### ISSUE TITLE
Merge duplicated ruleFailed() method for the rule : OIFITS_TABLE_UNKNOWN

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/oitools#5]
Currently we have two methods ruleFailed():
-ruleFailed(final Rule rule, final FitsHDU hdu, final String member)
-ruleFailed(final Rule rule, final String extName, final int extNb)

OIFITS_TABLE_UNKNOWN is the only rule that uses the second version of this method.
It is therefore a question of mutualising the code of these methods or of making sure that the OIFITS_TABLE_UNKNOWN  rule can use the common method.

**Comment by bourgesl** [comment]
Fix issue title & description to be more descriptive (unclear)

**Comment by Hitogoroshi** [comment]
Proposal: (in 1 time)
- Simplify writing checker.inspectRuleFailed (how to catch version of the file)
