### ISSUE TITLE
Fix extNb for FITS image HDU

### ISSUE THREAD

**Issue by Hitogoroshi** [JMMC-OpenDev/oitools#6]
Take into account the FitsImageHDU when counting the FITS HDU (extNb field)

**Comment by bourgesl** [comment]
Impact study then propose a solution

**Comment by Hitogoroshi** [comment]
Usages of FitsHDU.setExtNb [4 occurrences]

FitsImageLoader.java
createImageHDU
  522:  imageHDU.setExtNb(hduIndex);

OIFitsFile.java
addOiTable
  164:  oiTable.setExtNb(getNbOiTables());

OIFitsLoader.java
processHDUnits
  435:  oiTable.setExtNb(i);
  487:  oiTable.setExtNb(i);

**Comment by Hitogoroshi** [comment]
Usages of FitsImageLoader.load [6 occurrences]
OITools
FitsImageLoader.java
  161:  return load(absFilePath, firstOnly, false);

Test Packages
DumpFitsTest.java
    88:  FITS = FitsImageLoader.load(f, false, false);
LoadFitsTest.java
    87:  FITS = FitsImageLoader.load(f, false, false);
WriteFitsTest.java
    60:  final FitsImageFile srcFitsFile = FitsImageLoader.load(pathFile, false, false);

Usages of OIFitsLoader.loadOIFits [1 occurrence]
Test Packages
OITools
OIFitsViewer.java
  110:  final OIFitsFile oiFitsFile = OIFitsLoader.loadOIFits(this.checker, filename, true)

CreateOIFileV1Test.java
    82:  final OIFitsFile destOIFitsFile = OIFitsLoader.loadOIFits(absFilePath);

CreateOIFitsV2Test.java
  109:  final OIFitsFile destOIFitsFile = OIFitsLoader.loadOIFits(absFilePath);

WriteOIFitsTest.java
    61:  final OIFitsFile srcOIFitsFile = OIFitsLoader.loadOIFits(pathFile);
    73:  final OIFitsFile destOIFitsFile = OIFitsLoader.loadOIFits(fileTo);

**Comment by bourgesl** [comment]
Thanks for the usages.
What do you propose to test the bug & fix it ?

**Comment by Hitogoroshi** [comment]
During the analysis I do not have any problems when reading a file or its writing.
It would be necessary to review how indexes are managed during the creation of a memory structure.
